spring.application.name=dbmigration

spring.datasource.url=jdbc:postgresql://localhost:5432/flyway
spring.datasource.username=postgres
spring.datasource.password=8431362872
spring.jpa.hibernate.ddl-auto=none

# Flyway Configuration
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
